/* Git / GitHub for Bioinformatics — 互動式考題題庫（中英雙語版）
 * Bilingual question bank.
 * 題型 type: "single" | "multi" | "tf"
 * 單選 ans: "A"|"B"|"C"|"D" / 多選 ans: ["A","C"] / 是非 ans: "T"|"F"
 */
window.QUIZ_DATA = {
  git: {
    label: "Git / GitHub 互動考題",
    label_en: "Git / GitHub Interactive Quiz",
    labels_en: {
      "核心 Git 流程": "Core Git Pipeline",
      "進階主題": "Advanced Topics",
      "Step 1：安裝與設定 (Setup & Config)": "Step 1: Setup & Config",
      "Step 2：儲存庫基礎 (Repo Basics)": "Step 2: Repository Basics",
      "Step 3：檢視變更 (Inspecting)": "Step 3: Inspecting Changes",
      "Step 4：撤銷與時光旅行 (Undo)": "Step 4: Undoing & Time Travel",
      "Step 5：分支 (Branching)": "Step 5: Branching",
      "Step 6：合併與 Rebase": "Step 6: Merging & Rebasing",
      "Step 7：遠端與 GitHub 同步": "Step 7: Remotes & GitHub Sync",
      "Step 8：GitHub 協作 (PR & Review)": "Step 8: GitHub Collaboration",
      "Step 9：.gitignore & Git LFS": "Step 9: .gitignore & Git LFS",
      "Advanced：Git 工作流程": "Advanced: Git Workflows",
      "Advanced：GitHub Actions & CI/CD": "Advanced: GitHub Actions & CI/CD",
      "Advanced：可重現研究": "Advanced: Reproducibility"
    },
    subjects: {
      "核心 Git 流程": {

"Step 1：安裝與設定 (Setup & Config)": [
{ type:"single",
  stem:"自 2021/8/13 起，從本機 push 到 GitHub 時，HTTPS 連線不能再使用下列何者進行認證？",
  stem_en:"Since Aug 13, 2021, which authentication method is NO LONGER accepted when pushing to GitHub over HTTPS?",
  A:"SSH key", A_en:"SSH key",
  B:"Personal Access Token (PAT)", B_en:"Personal Access Token (PAT)",
  C:"帳號密碼（password）", C_en:"Account password",
  D:"GitHub Actions token", D_en:"GitHub Actions token",
  ans:"C",
  exp:"GitHub 於 2021/8/13 全面停止接受密碼認證 Git 操作，改用 PAT 或 SSH。",
  exp_en:"GitHub stopped accepting passwords for Git operations on Aug 13, 2021 — use PAT or SSH instead." },
{ type:"single",
  stem:"產生 SSH key 後，下列哪一個檔案絕對不可外傳？",
  stem_en:"After generating an SSH key, which file must NEVER be shared?",
  A:"~/.ssh/id_ed25519.pub", A_en:"~/.ssh/id_ed25519.pub",
  B:"~/.ssh/id_ed25519（私鑰）", B_en:"~/.ssh/id_ed25519 (private key)",
  C:"~/.ssh/known_hosts", C_en:"~/.ssh/known_hosts",
  D:"~/.gitconfig", D_en:"~/.gitconfig",
  ans:"B",
  exp:"私鑰外洩等同於把 GitHub 帳號交給對方，務必只上傳 .pub 公鑰。",
  exp_en:"Leaking the private key equals handing over your account — only ever upload the .pub public key." },
{ type:"single",
  stem:"想為「實驗室專案」使用實驗室 email，但保留全域 noreply email，最佳做法為？",
  stem_en:"You want a lab email only for lab projects, while keeping a global noreply email. Best practice?",
  A:"修改 ~/.gitconfig 全域 user.email", A_en:"Edit ~/.gitconfig globally",
  B:"在 repo 內執行 git config user.email lab@uni.edu", B_en:"Inside the repo run git config user.email lab@uni.edu",
  C:"每次 commit 都加 --author 旗標", C_en:"Pass --author on every commit",
  D:"修改 commit 後再 amend 改 email", D_en:"Amend each commit afterward",
  ans:"B",
  exp:"per-repo 設定會覆寫全域設定，最乾淨且不會誤用個人 email。",
  exp_en:"A per-repo setting overrides the global one — cleanest and least error-prone." },
{ type:"single",
  stem:"全域設定 git 預設分支名稱為 main 的正確指令是？",
  stem_en:"Which command globally sets the default branch name to 'main'?",
  A:"git config --global init.defaultBranch main", A_en:"git config --global init.defaultBranch main",
  B:"git branch -m main", B_en:"git branch -m main",
  C:"git defaultBranch main", C_en:"git defaultBranch main",
  D:"git init main", D_en:"git init main",
  ans:"A",
  exp:"init.defaultBranch 是 git config 的鍵；GitHub 自 2020 起以 main 為預設。",
  exp_en:"init.defaultBranch is the right config key; GitHub defaults to main since 2020." },
{ type:"multi",
  stem:"下列哪些做法可以提升 SSH 認證的安全性與可管理性？（多選）",
  stem_en:"Which practices improve SSH authentication security and manageability? (Multiple)",
  A:"每台機器各自產生 SSH key，分別加到 GitHub", A_en:"Generate a separate SSH key per machine and add each to GitHub",
  B:"為 SSH key 設定 passphrase", B_en:"Set a passphrase on the SSH key",
  C:"把私鑰 scp 到所有機器共用", C_en:"scp the private key to all machines for shared use",
  D:"為 GitHub SSH key 加機器名稱 label（如 laptop-2026）", D_en:"Label keys with machine names (e.g., laptop-2026)",
  ans:["A","B","D"],
  exp:"共用私鑰一旦洩漏無法定位來源；獨立 key + passphrase + label 才是最佳實踐。",
  exp_en:"Sharing a private key destroys revocation granularity; per-machine keys, passphrases, and labels are best practice." },
{ type:"tf",
  stem:"是非題：Personal Access Token (PAT) 一旦外洩，必須立刻在 GitHub Settings 撤銷。",
  stem_en:"True/False: A leaked Personal Access Token (PAT) must be revoked immediately in GitHub Settings.",
  ans:"T",
  exp:"PAT 等於密碼，外洩可被用以 push/讀取私有 repo，應第一時間撤銷並重新發。",
  exp_en:"A PAT acts like a password — leaks must be revoked instantly, then re-issued." },
{ type:"single",
  stem:"在 HPC 上 ssh -T git@github.com 顯示 'Connection refused'，最可能的原因？",
  stem_en:"On HPC, `ssh -T git@github.com` returns 'Connection refused'. Most likely cause?",
  A:"GitHub 暫停服務", A_en:"GitHub service outage",
  B:"防火牆封鎖 port 22", B_en:"Firewall blocks port 22",
  C:"SSH key 過期", C_en:"SSH key expired",
  D:"PAT 未啟用", D_en:"PAT not enabled",
  ans:"B",
  exp:"HPC 常封鎖 port 22；在 ~/.ssh/config 加 Hostname ssh.github.com / Port 443 可改走 HTTPS port。",
  exp_en:"HPCs often block port 22 — set ssh.github.com / Port 443 in ~/.ssh/config to use SSH-over-HTTPS." },
{ type:"single",
  stem:"以下何者為現代推薦的 SSH 演算法？",
  stem_en:"Which is the modern recommended SSH algorithm?",
  A:"ssh-rsa 1024 bits", A_en:"ssh-rsa 1024 bits",
  B:"DSA", B_en:"DSA",
  C:"ed25519", C_en:"ed25519",
  D:"ECDSA P-192", D_en:"ECDSA P-192",
  ans:"C",
  exp:"ed25519 比 RSA 短、快且更安全，是 OpenSSH 現代推薦。",
  exp_en:"ed25519 is shorter, faster, and more secure than RSA — modern OpenSSH default recommendation." },
{ type:"single",
  stem:"設定 git 預設編輯器為 VS Code 的正確指令？",
  stem_en:"How do you set VS Code as the default Git editor?",
  A:"git config core.editor code", A_en:"git config core.editor code",
  B:"git config --global core.editor \"code --wait\"", B_en:"git config --global core.editor \"code --wait\"",
  C:"export GIT_EDITOR=vscode", C_en:"export GIT_EDITOR=vscode",
  D:"git editor set code", D_en:"git editor set code",
  ans:"B",
  exp:"--wait 讓 git 暫停，等 VS Code 視窗關閉後再繼續，避免立刻退回終端。",
  exp_en:"--wait makes git block until the VS Code window is closed — without it, git resumes immediately." },
{ type:"tf",
  stem:"是非題：Fine-grained PAT 可指定僅能存取特定 repo 與特定權限，比 classic PAT 更安全。",
  stem_en:"True/False: A fine-grained PAT can be scoped to specific repos and permissions, making it safer than a classic PAT.",
  ans:"T",
  exp:"Fine-grained PAT 提供 repo 級權限與精細 scope，是 2022 後 GitHub 推薦的形式。",
  exp_en:"Fine-grained PATs offer repo-level and granular scopes — GitHub-recommended since 2022." }
,
{ type:"multi",
  stem:"全域 ~/.gitconfig 中常見的設定鍵（key）有哪些？（多選）",
  stem_en:"Which keys commonly appear in a global ~/.gitconfig? (Multiple)",
  A:"user.name / user.email", A_en:"user.name / user.email",
  B:"core.editor", B_en:"core.editor",
  C:"init.defaultBranch", C_en:"init.defaultBranch",
  D:"network.firewall", D_en:"network.firewall",
  ans:["A","B","C"],
  exp:"A、B、C 為 git 標準設定鍵；network.firewall 並非 git config key。",
  exp_en:"A, B, and C are real git config keys; network.firewall is not." },
{ type:"tf",
  stem:"是非題：repo 內 .git/config 的設定會覆寫 ~/.gitconfig 的同名設定。",
  stem_en:"True/False: A repo's .git/config overrides the global ~/.gitconfig for the same key.",
  ans:"T",
  exp:"local > global > system 是 git config 三層的優先順序。",
  exp_en:"local > global > system is git config's three-tier precedence order." }
],

"Step 2：儲存庫基礎 (Repo Basics)": [
{ type:"single",
  stem:"一個檔案剛被編輯過、但尚未 git add，它位於哪一個區域？",
  stem_en:"A file was just edited but not yet `git add`-ed. Which area is it in?",
  A:"Repository (.git/)", A_en:"Repository (.git/)",
  B:"Staging area (Index)", B_en:"Staging area (Index)",
  C:"Working directory（工作區）", C_en:"Working directory",
  D:"Remote", D_en:"Remote",
  ans:"C",
  exp:"工作區 = 磁碟上你看到的檔案；add 後才進 staging。",
  exp_en:"Working directory = the files you see on disk; only after `add` does it move to staging." },
{ type:"single",
  stem:"git commit -am \"msg\" 的行為為何？",
  stem_en:"What does `git commit -am \"msg\"` do?",
  A:"自動加入所有 tracked 與 untracked 檔案再 commit", A_en:"Stages all tracked and untracked files, then commits",
  B:"只 stage 已 tracked 檔案的變更並一併 commit；不會 add 新檔", B_en:"Stages only existing tracked files, then commits — does NOT add new untracked files",
  C:"等同 git commit --amend", C_en:"Equivalent to git commit --amend",
  D:"自動 push 到遠端", D_en:"Auto-pushes to remote",
  ans:"B",
  exp:"-a 只 stage 「已被 tracked」的修改，新檔仍需手動 add。",
  exp_en:"-a only stages already-tracked file changes — new files still need explicit `add`." },
{ type:"single",
  stem:"git clone --depth 1 之後，可以看到 2020 年的 commit 嗎？",
  stem_en:"After `git clone --depth 1`, can you see commits from 2020?",
  A:"可以，所有歷史都在", A_en:"Yes, full history is preserved",
  B:"不行，這是 shallow clone，只有最新一個 snapshot", B_en:"No — shallow clone only has the latest snapshot",
  C:"可以，但需要密碼", C_en:"Yes, but a password is required",
  D:"可以，但只在 main 分支", D_en:"Yes, only on main",
  ans:"B",
  exp:"--depth 1 為 shallow clone，省下載量但不能完整看 log。",
  exp_en:"--depth 1 is a shallow clone — saves bandwidth but lacks full log history." },
{ type:"single",
  stem:"git init 的作用為何？",
  stem_en:"What does `git init` do?",
  A:"從遠端下載整個 repo", A_en:"Downloads an entire repo from the remote",
  B:"在當前資料夾建立 .git/ 子目錄，使其成為 Git 儲存庫", B_en:"Creates a .git/ subfolder in the current dir, turning it into a Git repo",
  C:"建立第一個 commit", C_en:"Creates the first commit",
  D:"設定全域 user.name", D_en:"Sets global user.name",
  ans:"B",
  exp:"init 只是建立 .git/，不會自動 add 或 commit 任何檔案。",
  exp_en:"`init` only creates .git/; it does not stage or commit any files." },
{ type:"multi",
  stem:"下列哪些情境應使用 git clone 而非 git init？（多選）",
  stem_en:"In which scenarios should you use `git clone` instead of `git init`? (Multiple)",
  A:"加入既有 GitHub 上的開源專案", A_en:"Joining an existing open-source GitHub project",
  B:"自己建立全新的本地專案", B_en:"Starting a brand-new local project",
  C:"接手實驗室既有 repo 繼續工作", C_en:"Taking over an existing lab repo to continue work",
  D:"複製某論文公開的程式碼來重跑分析", D_en:"Copying a paper's published code to rerun analysis",
  ans:["A","C","D"],
  exp:"只有 B 屬於從零開始，應該 init；其餘皆為複製既有 repo。",
  exp_en:"Only B starts from scratch (init); the others copy an existing repo (clone)." },
{ type:"single",
  stem:"git add -p 的功用是？",
  stem_en:"What is `git add -p` for?",
  A:"一次加入所有檔案", A_en:"Stages all files at once",
  B:"進入 patch 模式，可逐個 hunk 決定是否 stage", B_en:"Enters patch mode — choose hunks individually to stage",
  C:"自動修正 commit message", C_en:"Auto-fixes commit messages",
  D:"刪除 .git/ 目錄", D_en:"Deletes the .git/ directory",
  ans:"B",
  exp:"patch 模式對「把混在一起的修改拆成多個邏輯 commit」極為實用。",
  exp_en:"Patch mode is invaluable for splitting mixed changes into separate logical commits." },
{ type:"tf",
  stem:"是非題：在已是 Git repo 的資料夾內再執行 git init 會建立巢狀 .git，通常造成混亂。",
  stem_en:"True/False: Running `git init` inside an existing Git repo creates a nested .git and typically causes confusion.",
  ans:"T",
  exp:"巢狀 repo 須改用 submodule；亂 init 會造成兩層追蹤錯亂。",
  exp_en:"Nested repos should use submodules; nested init causes overlapping tracking confusion." },
{ type:"single",
  stem:"哪個指令最能讓你以單行檢視最近 10 個 commit 摘要？",
  stem_en:"Which command best shows the last 10 commits in single-line summary form?",
  A:"git log -10", A_en:"git log -10",
  B:"git log --oneline -10", B_en:"git log --oneline -10",
  C:"git history 10", C_en:"git history 10",
  D:"git status -10", D_en:"git status -10",
  ans:"B",
  exp:"--oneline 把每個 commit 摘成一行；-10 限制筆數。",
  exp_en:"--oneline collapses each commit to one line; -10 caps the count." },
{ type:"single",
  stem:"以下何者最不應該被當作 commit message？",
  stem_en:"Which is the WORST commit message practice?",
  A:"\"fix: handle NA in MT% filter (#42)\"", A_en:"\"fix: handle NA in MT% filter (#42)\"",
  B:"\"Add SCTransform v2 option\"", B_en:"\"Add SCTransform v2 option\"",
  C:"\"asdf\"", C_en:"\"asdf\"",
  D:"\"docs: update README citation\"", D_en:"\"docs: update README citation\"",
  ans:"C",
  exp:"無意義訊息毀掉 git log 的價值；commit message 是給未來自己看的。",
  exp_en:"Meaningless messages destroy git log's value — commit messages are for future-you." },
{ type:"single",
  stem:"git clone 後想立刻切到 develop 分支，最簡潔的方法？",
  stem_en:"After `git clone`, what's the quickest way to switch to the `develop` branch?",
  A:"git clone --branch develop URL", A_en:"git clone --branch develop URL",
  B:"git clone URL && git delete main", B_en:"git clone URL && git delete main",
  C:"必須先 push 再 pull", C_en:"You must push then pull first",
  D:"git fork develop", D_en:"git fork develop",
  ans:"A",
  exp:"--branch (簡寫 -b) 直接 clone 並 checkout 該分支。",
  exp_en:"--branch (alias -b) clones and checks out that branch directly." }
,
{ type:"multi",
  stem:"以下哪些指令會「實際」建立 commit？（多選）",
  stem_en:"Which commands actually CREATE a commit? (Multiple)",
  A:"git commit -m \"...\"", A_en:"git commit -m \"...\"",
  B:"git commit --amend", B_en:"git commit --amend",
  C:"git add .", C_en:"git add .",
  D:"git merge --no-ff feature", D_en:"git merge --no-ff feature",
  ans:["A","B","D"],
  exp:"add 只動 staging；merge --no-ff 強制建立 merge commit；amend 取代上一 commit 也是建立新 SHA。",
  exp_en:"add only updates staging; merge --no-ff creates a merge commit; amend replaces the last commit with a new SHA." },
{ type:"tf",
  stem:"是非題：git commit -am 會自動將「未被 tracked」的新檔加入 commit。",
  stem_en:"True/False: `git commit -am` automatically commits new (untracked) files.",
  ans:"F",
  exp:"-a 只 stage 已 tracked 檔案的變更；新檔仍需先 git add。",
  exp_en:"-a only stages changes to already-tracked files; new files still need explicit git add." }
],

"Step 3：檢視變更 (Inspecting)": [
{ type:"single",
  stem:"git diff --staged 顯示的是什麼？",
  stem_en:"What does `git diff --staged` show?",
  A:"工作區 vs 上次 commit", A_en:"Working dir vs last commit",
  B:"暫存區 vs 上次 commit（即下一次 commit 的內容）", B_en:"Staging area vs last commit (what *will* be committed)",
  C:"當前分支 vs 遠端分支", C_en:"Current branch vs remote branch",
  D:"工作區 vs 暫存區", D_en:"Working dir vs staging",
  ans:"B",
  exp:"--staged（同 --cached）對比 index 與 HEAD，看即將 commit 的內容。",
  exp_en:"--staged (same as --cached) compares index to HEAD — preview of what's about to commit." },
{ type:"single",
  stem:"想知道 analysis.R 第 47 行最後被誰修改、在哪一個 commit，最佳指令是？",
  stem_en:"To find who last edited line 47 of analysis.R and in which commit, which command is best?",
  A:"git log analysis.R", A_en:"git log analysis.R",
  B:"git diff analysis.R", B_en:"git diff analysis.R",
  C:"git blame analysis.R", C_en:"git blame analysis.R",
  D:"git status", D_en:"git status",
  ans:"C",
  exp:"git blame 逐行顯示最後修改者與 commit SHA，再用 git show <SHA> 看完整 diff。",
  exp_en:"git blame shows per-line author/commit; drill into details with git show <SHA>." },
{ type:"single",
  stem:"git log -S \"deseq2\" 的作用？",
  stem_en:"What does `git log -S \"deseq2\"` do?",
  A:"搜尋 commit message 含 deseq2 的 commit", A_en:"Searches commits whose message contains 'deseq2'",
  B:"pickaxe 搜尋：找出新增或刪除字串 deseq2 的 commit", B_en:"Pickaxe search: finds commits where the string 'deseq2' was added or removed",
  C:"列出檔案內含 deseq2 的所有 commit", C_en:"Lists all commits whose files mention 'deseq2'",
  D:"設定 deseq2 為 commit author", D_en:"Sets deseq2 as commit author",
  ans:"B",
  exp:"-S 是 pickaxe，比 grep 更精準，常用於追字串首次出現／消失的時點。",
  exp_en:"-S is the pickaxe — precise for finding when a string was introduced or removed." },
{ type:"single",
  stem:"想搜尋 commit message 含 \"bug\" 的 commit，使用？",
  stem_en:"To find commits whose message contains 'bug', use?",
  A:"git log -S bug", A_en:"git log -S bug",
  B:"git log --grep=bug", B_en:"git log --grep=bug",
  C:"git diff bug", C_en:"git diff bug",
  D:"git show bug", D_en:"git show bug",
  ans:"B",
  exp:"--grep 搜 message；-S 搜內容差異。",
  exp_en:"--grep searches messages; -S searches content diffs." },
{ type:"single",
  stem:"git show abc1234 顯示什麼？",
  stem_en:"What does `git show abc1234` display?",
  A:"abc1234 分支的內容", A_en:"Branch 'abc1234' contents",
  B:"abc1234 這個 commit 的完整資訊與其引入的 diff", B_en:"Full info for commit abc1234 plus the diff it introduced",
  C:"專案所有 commit 列表", C_en:"List of all commits",
  D:"abc1234 的衝突清單", D_en:"abc1234's conflict list",
  ans:"B",
  exp:"git show <SHA> = commit metadata + 該 commit 的差異。",
  exp_en:"git show <SHA> = commit metadata plus the diff it introduces." },
{ type:"single",
  stem:"想看兩個分支 main 與 feature 的差異，正確指令？",
  stem_en:"To see differences between `main` and `feature` branches, the correct command is?",
  A:"git diff main feature", A_en:"git diff main feature",
  B:"git show main feature", B_en:"git show main feature",
  C:"git status main feature", C_en:"git status main feature",
  D:"git compare main feature", D_en:"git compare main feature",
  ans:"A",
  exp:"git diff branchA branchB 顯示 branchA→branchB 的差異。",
  exp_en:"git diff branchA branchB shows the diff from branchA to branchB." },
{ type:"multi",
  stem:"以下哪些是 git log 常用旗標？（多選）",
  stem_en:"Which are commonly used `git log` flags? (Multiple)",
  A:"--oneline", A_en:"--oneline",
  B:"--graph", B_en:"--graph",
  C:"--author=\"Alice\"", C_en:"--author=\"Alice\"",
  D:"--push", D_en:"--push",
  ans:["A","B","C"],
  exp:"--push 不存在；其餘三者皆為合法 log 旗標。",
  exp_en:"--push is not a valid log flag; the other three are common ones." },
{ type:"single",
  stem:"統一差異格式中 @@ -10,5 +10,7 @@ 的含義？",
  stem_en:"In unified diff, what does `@@ -10,5 +10,7 @@` mean?",
  A:"舊檔從第 10 行起 5 行、新檔從第 10 行起 7 行", A_en:"Old file: 5 lines starting at line 10; New file: 7 lines starting at line 10",
  B:"新增 10 行、刪除 5 行", B_en:"Added 10 lines, deleted 5",
  C:"行號 10 到 5 倒序", C_en:"Lines 10 to 5 reversed",
  D:"無意義雜訊", D_en:"Meaningless noise",
  ans:"A",
  exp:"hunk header 格式：-舊起點,行數 +新起點,行數。",
  exp_en:"Hunk header format: -oldStart,oldCount +newStart,newCount." },
{ type:"single",
  stem:"想以 ASCII 圖檢視所有分支的歷史，最常用組合？",
  stem_en:"To see all branches' history as an ASCII graph, the most common combo is?",
  A:"git log --status", A_en:"git log --status",
  B:"git log --oneline --graph --decorate --all", B_en:"git log --oneline --graph --decorate --all",
  C:"git log --tree", C_en:"git log --tree",
  D:"git history --all", D_en:"git history --all",
  ans:"B",
  exp:"oneline + graph + decorate + all 是「pretty log」必備四件套。",
  exp_en:"oneline + graph + decorate + all — the canonical 'pretty log' quartet." },
{ type:"tf",
  stem:"是非題：git show HEAD:path/to/file.R 可在不 checkout 的情況下檢視某 commit 中的檔案。",
  stem_en:"True/False: `git show HEAD:path/to/file.R` lets you inspect a file as of a specific commit without checking it out.",
  ans:"T",
  exp:"這是查歷史版本檔案內容的「不副作用」做法。",
  exp_en:"This is the side-effect-free way to read a historical file revision." }
,
{ type:"multi",
  stem:"以下哪些是 git diff 的合法目標？（多選）",
  stem_en:"Which are valid targets for `git diff`? (Multiple)",
  A:"git diff", A_en:"git diff",
  B:"git diff --staged", B_en:"git diff --staged",
  C:"git diff HEAD~3..HEAD", C_en:"git diff HEAD~3..HEAD",
  D:"git diff branch1..branch2", D_en:"git diff branch1..branch2",
  ans:["A","B","C","D"],
  exp:"四種皆為合法 diff 範圍；分別比較不同的兩棵 tree。",
  exp_en:"All four are valid diff ranges, each comparing two different trees." },
{ type:"tf",
  stem:"是非題：git bisect 可結合自動化測試腳本（git bisect run）自動找出 bug commit。",
  stem_en:"True/False: `git bisect run` can automate the binary search with a test script to find the bug commit.",
  ans:"T",
  exp:"提供一個 exit code 0=good / 非 0=bad 的腳本，bisect 自動跑完。",
  exp_en:"Provide a script returning 0=good / non-zero=bad; bisect runs it automatically." }
],

"Step 4：撤銷與時光旅行 (Undo)": [
{ type:"single",
  stem:"你 commit + push 後發現有 bug，且同事已 pull 了該 commit。最安全的修法為？",
  stem_en:"You committed and pushed a bug; collaborators already pulled. Safest fix?",
  A:"git reset --hard HEAD~1 後強推", A_en:"`git reset --hard HEAD~1` then force-push",
  B:"git revert <sha> 建立反向 commit 後 push", B_en:"`git revert <sha>` to create an inverse commit, then push",
  C:"刪除 .git/ 重來", C_en:"Delete .git/ and start over",
  D:"什麼都不做", D_en:"Do nothing",
  ans:"B",
  exp:"已推出的歷史不要 reset；revert 建立新 commit 反向修改，安全且不破壞同事的歷史。",
  exp_en:"Never reset published history — `revert` creates a new inverse commit that preserves collaborators' history." },
{ type:"single",
  stem:"git reset --soft HEAD~1 之後，剛才那筆 commit 的變更會位於？",
  stem_en:"After `git reset --soft HEAD~1`, the changes from that commit end up where?",
  A:"被永久刪除", A_en:"Permanently deleted",
  B:"留在暫存區（staged）", B_en:"Staged in the index",
  C:"留在工作區但未 staged", C_en:"In the working dir but unstaged",
  D:"還在 HEAD", D_en:"Still in HEAD",
  ans:"B",
  exp:"--soft 只移動 HEAD，index 與 working dir 都不動；變更仍在 staging。",
  exp_en:"--soft only moves HEAD; index and working dir untouched — changes remain staged." },
{ type:"single",
  stem:"剛才 reset --hard 意外刪除昨天的工作，第一步該嘗試？",
  stem_en:"You accidentally `reset --hard` and lost yesterday's work. First step?",
  A:"重灌作業系統", A_en:"Reinstall the OS",
  B:"git reflog 找出 dangling SHA", B_en:"`git reflog` to find the dangling SHA",
  C:"重新 clone repo", C_en:"Re-clone the repo",
  D:"git checkout --recover", D_en:"git checkout --recover",
  ans:"B",
  exp:"reflog 保存最近 90 天的 HEAD 移動歷史，找到 SHA 後可以 checkout 或建分支恢復。",
  exp_en:"reflog logs all HEAD moves for ~90 days — checkout or branch the lost SHA to recover." },
{ type:"single",
  stem:"git revert 與 git reset 的核心差異？",
  stem_en:"Core difference between `git revert` and `git reset`?",
  A:"revert 是建立反向 commit，不修改歷史；reset 是搬動 HEAD，會改寫歷史", A_en:"revert creates an inverse commit (history-preserving); reset moves HEAD (history-rewriting)",
  B:"revert 只能用於本地；reset 只能用於遠端", B_en:"revert is local-only; reset is remote-only",
  C:"兩者完全等價", C_en:"They are equivalent",
  D:"revert 永遠不安全", D_en:"revert is never safe",
  ans:"A",
  exp:"revert 對「已公開歷史」更安全；reset 適合尚未推出的本地修正。",
  exp_en:"revert is safer for published history; reset suits local-only changes." },
{ type:"single",
  stem:"git stash 適合下列何種情境？",
  stem_en:"When is `git stash` most useful?",
  A:"想丟掉所有未 push 的 commit", A_en:"Permanently discarding unpushed commits",
  B:"PI 突然要看別的東西，你需暫存當前未完成修改", B_en:"Your PI wants something else NOW and you need to set aside WIP",
  C:"修改 commit author 名稱", C_en:"Changing the commit author name",
  D:"取代 git reset", D_en:"Replacing git reset",
  ans:"B",
  exp:"stash 將未完成的改動暫存堆疊，事後 pop 回來繼續。",
  exp_en:"Stash shelves unfinished changes onto a stack — pop later to resume." },
{ type:"multi",
  stem:"以下哪些 reset 模式會改動工作區（working dir）？（多選）",
  stem_en:"Which `reset` modes alter the working directory? (Multiple)",
  A:"--soft", A_en:"--soft",
  B:"--mixed", B_en:"--mixed",
  C:"--hard", C_en:"--hard",
  D:"--keep", D_en:"--keep",
  ans:["C"],
  exp:"只有 --hard 會改動 working dir；soft/mixed/keep 都保留工作區。",
  exp_en:"Only --hard touches the working dir; soft/mixed/keep preserve it." },
{ type:"single",
  stem:"git commit --amend 主要用途為？",
  stem_en:"Primary use of `git commit --amend`?",
  A:"刪掉上一個 commit", A_en:"Deletes the last commit",
  B:"修改上一個 commit 的訊息或內容", B_en:"Edit the message or contents of the last commit",
  C:"建立新分支", C_en:"Creates a new branch",
  D:"force-push 上一個 commit", D_en:"Force-pushes the last commit",
  ans:"B",
  exp:"amend 會以新 SHA 取代上一個 commit；若已推出，需 force-push（且應避免）。",
  exp_en:"Amend replaces the last commit with a new SHA — if already pushed, force-push is needed (and usually undesired)." },
{ type:"tf",
  stem:"是非題：在共用分支上絕對不要 git push --force。",
  stem_en:"True/False: NEVER `git push --force` to a shared branch.",
  ans:"T",
  exp:"force-push 改寫遠端歷史，同事的 pull 會失敗或產生衝突歷史；對 main / develop 等共用分支禁忌。",
  exp_en:"Force-push rewrites remote history — collaborators' pulls break. Forbidden on main / develop." },
{ type:"single",
  stem:"git restore --staged file.R 的作用？",
  stem_en:"What does `git restore --staged file.R` do?",
  A:"刪除 file.R", A_en:"Deletes file.R",
  B:"把 file.R 從暫存區移回 unstaged（但工作區修改保留）", B_en:"Unstages file.R while keeping its working-dir changes",
  C:"撤銷整個 commit", C_en:"Reverts an entire commit",
  D:"切換到含 file.R 的分支", D_en:"Switches to a branch containing file.R",
  ans:"B",
  exp:"--staged 取消 stage；不加 --staged 則回到 HEAD（丟掉工作區修改）。",
  exp_en:"--staged unstages only; without it, restore reverts the working dir to HEAD (losing edits)." },
{ type:"single",
  stem:"reflog 預設保留多久？",
  stem_en:"How long does reflog retain entries by default?",
  A:"7 天", A_en:"7 days",
  B:"30 天", B_en:"30 days",
  C:"90 天（一般 ref）；30 天（unreachable ref）", C_en:"90 days (reachable); 30 days (unreachable)",
  D:"永久", D_en:"Forever",
  ans:"C",
  exp:"預設 gc.reflogExpire=90, gc.reflogExpireUnreachable=30；可調整。",
  exp_en:"Defaults: gc.reflogExpire=90, gc.reflogExpireUnreachable=30. Tunable." }
,
{ type:"multi",
  stem:"以下哪些操作可從 reflog 中恢復？（多選）",
  stem_en:"Which operations are recoverable via reflog? (Multiple)",
  A:"git reset --hard 後遺失的 commit", A_en:"Commits lost after `git reset --hard`",
  B:"git branch -D 刪除的分支 tip", B_en:"The tip of a branch deleted by `git branch -D`",
  C:"git rebase 後遺失的舊 commit", C_en:"Old commits left behind after `git rebase`",
  D:"被 `git push --force` 蓋掉的遠端 commit", D_en:"Remote commits overwritten by `git push --force`",
  ans:["A","B","C"],
  exp:"reflog 是本地 HEAD 移動歷史；不會記錄遠端被覆蓋的 commit（除非有人本機也保留它）。",
  exp_en:"Reflog tracks local HEAD moves; it cannot recover remote commits force-overwritten unless someone has a local copy." },
{ type:"tf",
  stem:"是非題：git stash pop 會把 stash 套用到目前分支並從 stash list 移除該筆。",
  stem_en:"True/False: `git stash pop` applies the stash to the current branch AND drops it from the stash list.",
  ans:"T",
  exp:"`stash apply` 只套用不刪除；`pop` = apply + drop。",
  exp_en:"`stash apply` only applies; `pop` = apply + drop." }
],

"Step 5：分支 (Branching)": [
{ type:"single",
  stem:"Git 中的「分支」(branch) 技術上是？",
  stem_en:"Technically, a Git 'branch' is?",
  A:"專案檔案的完整副本", A_en:"A complete copy of the project files",
  B:"指向某一 commit 的輕量級指標（pointer）", B_en:"A lightweight pointer to a commit",
  C:"資料庫 schema", C_en:"A database schema",
  D:"GitHub 上的目錄", D_en:"A folder on GitHub",
  ans:"B",
  exp:"branch 在 .git/refs/heads/ 下是一個 41-byte 檔案，內容是該 commit 的 SHA。",
  exp_en:"A branch is a 41-byte file in .git/refs/heads/ holding the SHA of the commit." },
{ type:"single",
  stem:"執行 git checkout <SHA> 後 Git 警告 'You are in detached HEAD state'，意義為？",
  stem_en:"After `git checkout <SHA>` Git warns 'You are in detached HEAD state'. Meaning?",
  A:"電腦壞了", A_en:"Your computer is broken",
  B:"HEAD 不指向任何分支；此時新 commit 沒有分支引用，未建分支會被當作 dangling", B_en:"HEAD doesn't point to any branch; new commits without a new branch become dangling",
  C:"必須立刻 push", C_en:"You must push immediately",
  D:"reset 失敗", D_en:"Reset failed",
  ans:"B",
  exp:"在 detached HEAD 做 commit 後若沒 git branch <name> 接住，會在切換分支時遺失。",
  exp_en:"Commits made in detached HEAD without `git branch <name>` will be lost on next switch." },
{ type:"single",
  stem:"git branch -d 與 git branch -D 的差異？",
  stem_en:"Difference between `git branch -d` and `git branch -D`?",
  A:"-d 強制刪除；-D 安全刪除", A_en:"-d force; -D safe",
  B:"-d 安全（若未合併會拒絕）；-D 強制刪除（會遺失未合併 commit）", B_en:"-d is safe (refuses if unmerged); -D forces (may lose unmerged commits)",
  C:"完全相同", C_en:"They are identical",
  D:"-d 刪本地；-D 刪遠端", D_en:"-d local; -D remote",
  ans:"B",
  exp:"小寫 d 為「delete if merged」；大寫 D 強制。",
  exp_en:"Lower-case d only deletes merged branches; upper-case D forces deletion." },
{ type:"single",
  stem:"以下何者為「建立並切換到 new-feature」分支的最簡指令？",
  stem_en:"Which is the shortest way to create AND switch to a new branch `new-feature`?",
  A:"git switch -c new-feature", A_en:"git switch -c new-feature",
  B:"git branch new-feature && git switch new-feature", B_en:"git branch new-feature && git switch new-feature",
  C:"git create new-feature", C_en:"git create new-feature",
  D:"git new new-feature", D_en:"git new new-feature",
  ans:"A",
  exp:"switch -c 一次完成；checkout -b 也可（較舊指令）。",
  exp_en:"`switch -c` does both; `checkout -b` is the older equivalent." },
{ type:"single",
  stem:"列出所有分支（含遠端追蹤分支）的指令？",
  stem_en:"How do you list all branches including remote-tracking?",
  A:"git branch -a", A_en:"git branch -a",
  B:"git branch -r", B_en:"git branch -r",
  C:"git branch --all-remote", C_en:"git branch --all-remote",
  D:"git list-branches", D_en:"git list-branches",
  ans:"A",
  exp:"-a = all（本地 + 遠端追蹤）；-r 僅遠端。",
  exp_en:"-a = all (local + remote-tracking); -r is remote-only." },
{ type:"single",
  stem:"git branch --merged 的作用？",
  stem_en:"What does `git branch --merged` show?",
  A:"列出已合併到當前分支的分支", A_en:"Lists branches already merged into the current branch",
  B:"列出衝突中的分支", B_en:"Lists branches with conflicts",
  C:"自動合併所有分支", C_en:"Automatically merges all branches",
  D:"刪除已合併分支", D_en:"Deletes merged branches",
  ans:"A",
  exp:"配合 -d 可以批次清理已合併的舊 feature branches。",
  exp_en:"Combine with -d to batch-delete already-merged feature branches." },
{ type:"tf",
  stem:"是非題：在 Git 中切換分支前，未 commit 的修改可能阻止切換，但用 git stash 暫存後再 switch 是常見做法。",
  stem_en:"True/False: Uncommitted changes may block branch switching, but `git stash` is a common workaround.",
  ans:"T",
  exp:"若修改與目標分支衝突，Git 會擋下；stash 把改動收到堆疊後即可切換。",
  exp_en:"If changes conflict with the target branch, Git refuses; `git stash` saves them so you can switch." },
{ type:"single",
  stem:"重新命名當前分支為 hotfix 的指令？",
  stem_en:"Rename the current branch to `hotfix`:",
  A:"git branch -m hotfix", A_en:"git branch -m hotfix",
  B:"git rename hotfix", B_en:"git rename hotfix",
  C:"git switch -r hotfix", C_en:"git switch -r hotfix",
  D:"git checkout -rename hotfix", D_en:"git checkout -rename hotfix",
  ans:"A",
  exp:"-m = move (rename)；指定兩個參數則為 old-name new-name。",
  exp_en:"-m = move (rename); with two args: old-name new-name." },
{ type:"single",
  stem:"git switch 相較於舊版 git checkout 切換分支的主要優點？",
  stem_en:"Main advantage of `git switch` over the old `git checkout` for branch switching?",
  A:"執行速度快 10 倍", A_en:"10× faster",
  B:"語意更明確，與 git restore 一起取代 checkout 的多重職責", B_en:"Clearer semantics — together with `git restore` it splits checkout's overloaded duties",
  C:"自動 push", C_en:"Auto-pushes",
  D:"支援 Windows 多視窗", D_en:"Supports multi-window Windows",
  ans:"B",
  exp:"Git 2.23 引入 switch/restore，把 checkout 的兩種任務（切分支 / 恢復檔案）分開。",
  exp_en:"Git 2.23 introduced switch/restore to split checkout's two roles (switch branch / restore files)." },
{ type:"multi",
  stem:"以下哪些是建立 branch 的好時機？（多選）",
  stem_en:"Which are good times to create a branch? (Multiple)",
  A:"嘗試實驗性的程式碼", A_en:"Trying experimental code",
  B:"修改超過 1 小時的 feature", B_en:"Features taking more than ~1 hour",
  C:"多人共同協作不同任務", C_en:"Multiple people working on different tasks",
  D:"修改一個 typo（commit 直接寫 main）", D_en:"Fixing a typo (commit straight to main)",
  ans:["A","B","C"],
  exp:"branch 幾乎零成本，多用無妨；極小且獨立的修改視團隊規範。",
  exp_en:"Branches are essentially free — use them freely; tiny isolated fixes depend on team policy." }
,
{ type:"multi",
  stem:"關於 Git 分支，下列敘述哪些正確？（多選）",
  stem_en:"Which statements about Git branches are correct? (Multiple)",
  A:"建立 branch 幾乎沒有成本（41 byte 檔案）", A_en:"Creating a branch is nearly free (41-byte file)",
  B:"branch -d 在分支已合併到當前分支時才會成功", B_en:"`branch -d` succeeds only if the branch is merged into the current branch",
  C:"git switch -c 與 git checkout -b 等價", C_en:"`git switch -c` is equivalent to `git checkout -b`",
  D:"分支必須先 push 才能在本地使用", D_en:"A branch must be pushed before it can be used locally",
  ans:["A","B","C"],
  exp:"D 錯：branch 是純本地概念，push 與否與「能否使用」無關。",
  exp_en:"D is wrong: branches are local concepts — pushing is unrelated to local usability." },
{ type:"tf",
  stem:"是非題：在 detached HEAD 狀態下做的 commit 若沒有用 git branch 接住，切換分支後便可能透過 reflog 找回。",
  stem_en:"True/False: Commits made in detached HEAD without `git branch` can still be recovered via reflog after switching.",
  ans:"T",
  exp:"reflog 紀錄 HEAD 移動軌跡，仍然能在 90 天內找回 SHA。",
  exp_en:"Reflog records HEAD moves — the SHA is still recoverable within ~90 days." }
],

"Step 6：合併與 Rebase": [
{ type:"single",
  stem:"git merge 與 git rebase 的核心差異？",
  stem_en:"Core difference between `git merge` and `git rebase`?",
  A:"merge 建立 merge commit 保留兩條歷史；rebase 將 commits 重放至新基點並產生新 SHA", A_en:"merge creates a merge commit preserving both histories; rebase replays commits onto a new base with new SHAs",
  B:"merge 自動衝突解決；rebase 無法解衝突", B_en:"merge auto-resolves conflicts; rebase cannot",
  C:"完全相同", C_en:"They are identical",
  D:"rebase 只在 GitHub 上能用", D_en:"rebase only works on GitHub",
  ans:"A",
  exp:"merge 保留分支結構；rebase 改寫歷史為線性。",
  exp_en:"merge preserves branch shape; rebase rewrites to a linear history." },
{ type:"single",
  stem:"執行 git rebase main（在 feature 上）的結果？",
  stem_en:"What happens when you run `git rebase main` on `feature`?",
  A:"main 被刪除", A_en:"main is deleted",
  B:"feature 的 commit 被重新套用到 main 最新 tip，產生新 SHA", B_en:"feature's commits are replayed on the tip of main, with new SHAs",
  C:"main 被 force-push 到 feature", C_en:"main is force-pushed to feature",
  D:"feature 變為 detached HEAD", D_en:"feature becomes detached HEAD",
  ans:"B",
  exp:"rebase 將你 feature 的 commit「移植」到 main 新尖端後重做。",
  exp_en:"Rebase replants your feature commits onto main's tip." },
{ type:"single",
  stem:"合併出現衝突時，正確的處理順序？",
  stem_en:"When a merge conflict appears, what's the correct workflow?",
  A:"git revert 直接撤銷", A_en:"`git revert` immediately",
  B:"編輯衝突檔，移除標記，git add，最後 commit / rebase --continue", B_en:"Edit conflicted files, remove markers, `git add`, then `commit` / `rebase --continue`",
  C:"force-push 強制覆蓋", C_en:"Force-push to overwrite",
  D:"刪除 .git/", D_en:"Delete .git/",
  ans:"B",
  exp:"標準衝突修復循環；不想繼續可用 --abort 還原。",
  exp_en:"Standard conflict resolution; use `--abort` to bail out cleanly." },
{ type:"single",
  stem:"fast-forward (FF) merge 發生在何種情況？",
  stem_en:"A fast-forward (FF) merge occurs when?",
  A:"目標分支自分叉後完全沒有新 commit", A_en:"The target branch has had no new commits since the source branched off",
  B:"目標分支有衝突", B_en:"The target branch has conflicts",
  C:"來源分支只有一個 commit", C_en:"The source branch has only one commit",
  D:"使用 --no-ff 旗標", D_en:"You used --no-ff",
  ans:"A",
  exp:"FF 條件：目標分支可由來源分支「直線」到達——只需移動指標即可完成。",
  exp_en:"FF condition: the target is directly reachable from the source — Git just moves the pointer forward." },
{ type:"tf",
  stem:"是非題：絕對不要 rebase 已推到共用分支的 commit。",
  stem_en:"True/False: NEVER rebase commits already pushed to a shared branch.",
  ans:"T",
  exp:"rebase 改寫 SHA，會破壞別人的 history；這就是「黃金法則」。",
  exp_en:"Rebase rewrites SHAs — breaks others' history. This is the 'golden rule of rebasing'." },
{ type:"single",
  stem:"想把另一分支某個 commit「單獨」搬到當前分支，最合適指令？",
  stem_en:"To copy a single commit from another branch to your current branch, the best command is?",
  A:"git merge --squash", A_en:"git merge --squash",
  B:"git cherry-pick <sha>", B_en:"git cherry-pick <sha>",
  C:"git rebase -i HEAD~10", C_en:"git rebase -i HEAD~10",
  D:"git reset --hard <sha>", D_en:"git reset --hard <sha>",
  ans:"B",
  exp:"cherry-pick 把單個 commit 套到當前分支，常用於熱修。",
  exp_en:"cherry-pick applies one commit onto the current branch — common for hotfixes." },
{ type:"single",
  stem:"git rebase -i HEAD~5 的用途？",
  stem_en:"Purpose of `git rebase -i HEAD~5`?",
  A:"開啟編輯器，互動式地對最近 5 個 commit 進行 squash/reword/edit/drop", A_en:"Opens an editor to interactively squash/reword/edit/drop the last 5 commits",
  B:"刪除最近 5 個 commit", B_en:"Deletes the last 5 commits",
  C:"檢視最近 5 個 commit 的 diff", C_en:"Views the diff of the last 5 commits",
  D:"無法執行", D_en:"Not a valid command",
  ans:"A",
  exp:"interactive rebase 是「整理本地 commit」的主力工具——push 前清潔好歷史。",
  exp_en:"Interactive rebase is the main tool for tidying local commits before pushing." },
{ type:"single",
  stem:"git merge --squash feature 的行為？",
  stem_en:"What does `git merge --squash feature` do?",
  A:"建立 merge commit 並保留 feature 所有 commit", A_en:"Creates a merge commit preserving all of feature's commits",
  B:"把 feature 的所有變更折疊成一個 staged change，需自行 commit", B_en:"Collapses feature's changes into one staged change — you commit it yourself",
  C:"自動 push 到遠端", C_en:"Auto-pushes to remote",
  D:"刪除 feature", D_en:"Deletes feature",
  ans:"B",
  exp:"squash merge 不建立 merge commit，feature 多個 commit 變成一筆乾淨的 commit。",
  exp_en:"Squash merge doesn't create a merge commit — feature's many commits become one tidy commit." },
{ type:"single",
  stem:"在 GitHub 上 PR 合併按鈕的「Rebase and merge」會發生什麼？",
  stem_en:"On GitHub, the 'Rebase and merge' button does what?",
  A:"建立 merge commit", A_en:"Creates a merge commit",
  B:"將 PR commits rebase 至目標分支再 fast-forward，產生線性歷史", B_en:"Rebases the PR's commits onto the target branch then fast-forwards — linear history",
  C:"squash 所有 commit 為 1 個", C_en:"Squashes all commits into one",
  D:"關閉 PR 而不合併", D_en:"Closes the PR without merging",
  ans:"B",
  exp:"Rebase and merge 產生線性歷史；squash and merge 才是壓成一個 commit。",
  exp_en:"'Rebase and merge' gives a linear history; 'Squash and merge' is what flattens to one commit." },
{ type:"multi",
  stem:"以下哪些是衝突檔案中會看到的標記？（多選）",
  stem_en:"Which markers appear inside a conflicted file? (Multiple)",
  A:"<<<<<<< HEAD", A_en:"<<<<<<< HEAD",
  B:"=======", B_en:"=======",
  C:">>>>>>> feature", C_en:">>>>>>> feature",
  D:"!!!!!!! CONFLICT", D_en:"!!!!!!! CONFLICT",
  ans:["A","B","C"],
  exp:"標準衝突三段標記為 <<<、===、>>>；!!! 不是 Git 的標記。",
  exp_en:"Standard conflict markers are <<<, ===, >>>; !!! is not Git's." }
,
{ type:"multi",
  stem:"以下哪些情境屬於「黃金法則」禁止的操作？（多選）",
  stem_en:"Which scenarios are forbidden by the 'golden rule' of rebasing? (Multiple)",
  A:"rebase 自己尚未 push 的本地分支", A_en:"Rebasing your own un-pushed local branch",
  B:"rebase 已 push 到共用 main 的 commit", B_en:"Rebasing commits already pushed to shared main",
  C:"force-push 共用分支以收乾淨歷史", C_en:"Force-pushing a shared branch to clean history",
  D:"用 interactive rebase 整理 PR 前的個人分支", D_en:"Interactive-rebasing your personal pre-PR branch",
  ans:["B","C"],
  exp:"A、D 為個人分支整理，不違反黃金法則；B、C 改寫他人共用歷史，禁忌。",
  exp_en:"A and D are personal tidying — allowed. B and C rewrite shared history — forbidden." },
{ type:"tf",
  stem:"是非題：fast-forward merge 不會建立 merge commit。",
  stem_en:"True/False: A fast-forward merge does NOT create a merge commit.",
  ans:"T",
  exp:"FF 只移動指標；要強制建立 merge commit 須加 --no-ff。",
  exp_en:"FF only advances the pointer; force a merge commit with --no-ff." }
],

"Step 7：遠端與 GitHub 同步": [
{ type:"single",
  stem:"想知道遠端是否有更新但不影響本地工作區，最安全的指令？",
  stem_en:"Safest command to check the remote without touching your working dir?",
  A:"git pull", A_en:"git pull",
  B:"git fetch", B_en:"git fetch",
  C:"git push", C_en:"git push",
  D:"git reset --hard origin/main", D_en:"git reset --hard origin/main",
  ans:"B",
  exp:"fetch 只下載 refs，不修改 working dir 與當前分支。",
  exp_en:"`fetch` only downloads refs; it leaves your working dir and current branch alone." },
{ type:"single",
  stem:"git pull 等於什麼？",
  stem_en:"`git pull` is equivalent to what combination?",
  A:"git fetch + git merge origin/<branch>", A_en:"git fetch + git merge origin/<branch>",
  B:"git push + git fetch", B_en:"git push + git fetch",
  C:"git clone + git checkout", C_en:"git clone + git checkout",
  D:"git fetch + git reset --hard", D_en:"git fetch + git reset --hard",
  ans:"A",
  exp:"預設 pull = fetch + merge；可設定 pull.rebase=true 改為 fetch + rebase。",
  exp_en:"Default pull = fetch + merge; with pull.rebase=true it's fetch + rebase." },
{ type:"single",
  stem:"git push 失敗顯示 'Updates were rejected (non-fast-forward)'，原因？",
  stem_en:"`git push` fails with 'Updates were rejected (non-fast-forward)'. Why?",
  A:"認證錯誤", A_en:"Authentication error",
  B:"遠端有你本地沒有的 commit；需先 pull/fetch", B_en:"Remote has commits you don't — pull/fetch first",
  C:"main 被刪除", C_en:"main was deleted",
  D:"分支名稱衝突", D_en:"Branch name conflict",
  ans:"B",
  exp:"non-fast-forward = 遠端走在你前面；先整合再 push。",
  exp_en:"Non-fast-forward = remote moved ahead; integrate before pushing." },
{ type:"single",
  stem:"新分支 feature-x push 並設定 upstream，最簡潔的指令？",
  stem_en:"Push new branch `feature-x` and set its upstream — shortest command?",
  A:"git push origin feature-x", A_en:"git push origin feature-x",
  B:"git push -u origin feature-x", B_en:"git push -u origin feature-x",
  C:"git track feature-x", C_en:"git track feature-x",
  D:"git upstream set feature-x", D_en:"git upstream set feature-x",
  ans:"B",
  exp:"-u（--set-upstream）讓後續 push/pull 不需再指定 origin。",
  exp_en:"-u (--set-upstream) means future push/pull don't need to specify origin." },
{ type:"single",
  stem:"想把 origin URL 從 HTTPS 換成 SSH，正確指令？",
  stem_en:"Change origin's URL from HTTPS to SSH — which command?",
  A:"git remote add origin git@github.com:user/repo.git", A_en:"git remote add origin git@github.com:user/repo.git",
  B:"git remote set-url origin git@github.com:user/repo.git", B_en:"git remote set-url origin git@github.com:user/repo.git",
  C:"git remote rename origin", C_en:"git remote rename origin",
  D:"git url set ssh", D_en:"git url set ssh",
  ans:"B",
  exp:"set-url 修改既有 remote 的 URL；add 會因名稱已存在報錯。",
  exp_en:"set-url updates an existing remote's URL; add would error because origin already exists." },
{ type:"single",
  stem:"在 fork workflow 中，「上游官方 repo」通常以何名稱新增為 remote？",
  stem_en:"In a fork workflow, what is the canonical upstream repo typically named as a remote?",
  A:"upstream", A_en:"upstream",
  B:"origin", B_en:"origin",
  C:"public", C_en:"public",
  D:"main", D_en:"main",
  ans:"A",
  exp:"慣例：origin = 自己的 fork；upstream = 官方 repo。",
  exp_en:"Convention: origin = your fork; upstream = the canonical repo." },
{ type:"tf",
  stem:"是非題：git fetch origin 永遠不會修改你的工作區（working dir）。",
  stem_en:"True/False: `git fetch origin` will never alter your working directory.",
  ans:"T",
  exp:"fetch 只更新遠端追蹤分支與物件，不動工作區或當前分支。",
  exp_en:"Fetch only updates remote-tracking refs and objects — not the working tree or current branch." },
{ type:"single",
  stem:"git branch -vv 的功用？",
  stem_en:"What does `git branch -vv` show?",
  A:"刪除分支前的二次驗證", A_en:"Double-confirms branch deletion",
  B:"列出本地分支以及它們追蹤的遠端分支與差距", B_en:"Lists local branches with their tracked remote and divergence info",
  C:"列出所有 verbose 設定", C_en:"Lists all verbose settings",
  D:"列出 conflict 中的分支", D_en:"Lists branches in conflict",
  ans:"B",
  exp:"-vv 比 -v 多顯示 upstream 與 ahead/behind 計數。",
  exp_en:"-vv vs -v: extra column showing upstream and ahead/behind counts." },
{ type:"single",
  stem:"git config pull.rebase true 設定後，git pull 將？",
  stem_en:"After `git config pull.rebase true`, `git pull` will?",
  A:"完全停止運作", A_en:"Stop working entirely",
  B:"執行 fetch + rebase（而非 fetch + merge）", B_en:"Run fetch + rebase (instead of fetch + merge)",
  C:"自動 push", C_en:"Auto-push",
  D:"切到 main 分支", D_en:"Switch to main",
  ans:"B",
  exp:"rebase 拉平歷史；merge 保留合併 commit。設 true 適合喜歡線性歷史者。",
  exp_en:"Rebase flattens history; merge preserves merge commits. true suits linear-history fans." },
{ type:"single",
  stem:"HPC 防火牆封鎖 port 22，最佳替代方案？",
  stem_en:"HPC firewall blocks port 22 — best workaround?",
  A:"放棄使用 Git", A_en:"Give up using Git",
  B:"在 ~/.ssh/config 將 github.com 改走 ssh.github.com port 443", B_en:"In ~/.ssh/config, route github.com via ssh.github.com on port 443",
  C:"用 USB 拷貝程式碼", C_en:"USB-copy code instead",
  D:"用 telnet", D_en:"Use telnet",
  ans:"B",
  exp:"SSH-over-HTTPS port 443 是官方 workaround，多數防火牆放行。",
  exp_en:"SSH-over-HTTPS on port 443 is the official workaround — most firewalls allow it." }
,
{ type:"multi",
  stem:"關於 git fetch，下列敘述哪些正確？（多選）",
  stem_en:"Which statements about `git fetch` are correct? (Multiple)",
  A:"下載遠端 refs 與 objects 到本地", A_en:"Downloads remote refs and objects locally",
  B:"更新 remote-tracking branch（如 origin/main）", B_en:"Updates remote-tracking branches (e.g., origin/main)",
  C:"修改你的工作區檔案", C_en:"Modifies your working-tree files",
  D:"自動合併到當前分支", D_en:"Auto-merges into the current branch",
  ans:["A","B"],
  exp:"C/D 是 pull 的行為；fetch 故意不動工作區，是最安全的同步指令。",
  exp_en:"C/D describe pull behavior; fetch deliberately leaves the working tree untouched — safest sync." },
{ type:"tf",
  stem:"是非題：在 fork workflow 中，定期執行 git fetch upstream 並合併進你的 main 是同步上游變更的標準做法。",
  stem_en:"True/False: In a fork workflow, periodically running `git fetch upstream` and merging into your main is the standard way to stay in sync with upstream.",
  ans:"T",
  exp:"fork 後上游持續演進，需定期同步，否則 PR 容易產生衝突。",
  exp_en:"Upstream evolves after forking; periodic syncing is essential to avoid PR conflicts." }
],

"Step 8：GitHub 協作 (PR & Review)": [
{ type:"single",
  stem:"要對 Seurat 提出修正建議，最正確的起手式？",
  stem_en:"To suggest a fix to Seurat, the correct opening move is?",
  A:"直接 push 到 Seurat 的 main 分支", A_en:"Push directly to Seurat's main branch",
  B:"Fork Seurat 到自己帳號 → clone fork → 開分支修改 → push → 對 upstream 開 PR", B_en:"Fork Seurat → clone your fork → branch + fix → push → open PR to upstream",
  C:"寄 email 給作者", C_en:"Email the author",
  D:"在 issue 留下程式碼後等他們複製", D_en:"Paste code in an issue and wait",
  ans:"B",
  exp:"無 write 權限時必先 fork；標準 OSS 貢獻流程。",
  exp_en:"Without write access, you must fork first — standard OSS contribution flow." },
{ type:"single",
  stem:"PR 描述中寫 'Fixes #42' 並合併後，issue #42 會？",
  stem_en:"With 'Fixes #42' in the PR description, what happens to issue #42 when merged?",
  A:"被自動關閉", A_en:"It auto-closes",
  B:"被自動刪除", B_en:"It's auto-deleted",
  C:"轉成 PR", C_en:"Turns into a PR",
  D:"無變化", D_en:"No change",
  ans:"A",
  exp:"關鍵字 (Closes/Fixes/Resolves #N) 觸發 issue 自動關閉。",
  exp_en:"Keywords (Closes/Fixes/Resolves #N) trigger automatic issue closure on merge." },
{ type:"single",
  stem:"被 reviewer 要求修改後，作者應該？",
  stem_en:"After a reviewer requests changes, the author should?",
  A:"force-push 重寫整個 PR", A_en:"Force-push to rewrite the entire PR",
  B:"在同一分支補新 commit，PR 自動更新（review thread 不丟失）", B_en:"Push new commits to the same branch — the PR updates automatically and review threads stay anchored",
  C:"開新 PR 取代舊的", C_en:"Open a new PR replacing the old one",
  D:"關閉 PR", D_en:"Close the PR",
  ans:"B",
  exp:"force-push 會使 reviewer 失去評論定位；補 commit 是標準做法。",
  exp_en:"Force-push detaches reviewer comments — adding commits is the standard approach." },
{ type:"single",
  stem:"Draft PR 的主要用途為？",
  stem_en:"What is a Draft PR for?",
  A:"自動合併", A_en:"Auto-merging",
  B:"開啟以分享 WIP、觸發 CI，但明確標示尚未準備好被 review", B_en:"Share WIP and run CI while signaling 'not ready for review'",
  C:"刪除某 commit", C_en:"Deletes a commit",
  D:"轉成 issue", D_en:"Converts to an issue",
  ans:"B",
  exp:"Draft 讓你早期取得 CI 結果而不打擾 reviewer。",
  exp_en:"Drafts give you early CI feedback without pinging reviewers prematurely." },
{ type:"single",
  stem:"GitHub PR 合併按鈕中，「Squash and merge」會？",
  stem_en:"GitHub PR's 'Squash and merge' button does what?",
  A:"建立 merge commit", A_en:"Creates a merge commit",
  B:"把 PR 中所有 commit 壓成一個 commit 後合併", B_en:"Collapses all PR commits into one before merging",
  C:"rebase 不合併", C_en:"Rebases without merging",
  D:"force-push", D_en:"Force-pushes",
  ans:"B",
  exp:"產出單一 commit 的乾淨主線歷史，但會遺失原 PR 多個 commit 訊息。",
  exp_en:"Produces a single tidy commit on main — but discards individual PR commit messages." },
{ type:"multi",
  stem:"GitHub CLI（gh）可以做哪些？（多選）",
  stem_en:"Which can the GitHub CLI (gh) do? (Multiple)",
  A:"gh pr create", A_en:"gh pr create",
  B:"gh release create", B_en:"gh release create",
  C:"gh issue list", C_en:"gh issue list",
  D:"執行 cellranger count", D_en:"Run `cellranger count`",
  ans:["A","B","C"],
  exp:"前三者皆為 gh 內建子指令；cellranger 與 gh 無關。",
  exp_en:"All but D are gh subcommands; cellranger is unrelated." },
{ type:"tf",
  stem:"是非題：在共用專案中，作者不應自行合併自己的 PR（即使有權限）。",
  stem_en:"True/False: On shared projects, authors should not merge their own PRs — even if they can.",
  ans:"T",
  exp:"PR 的價值在於 review；自合等於跳過 review。",
  exp_en:"The whole point of PRs is review — self-merging skips that safeguard." },
{ type:"single",
  stem:"與 review 留言不同，「Suggested changes」功能可讓？",
  stem_en:"Unlike normal review comments, GitHub's 'Suggested changes' feature lets the author?",
  A:"自動關閉 PR", A_en:"Auto-close the PR",
  B:"以一鍵 commit 接受 reviewer 提的具體修改", B_en:"Accept the reviewer's exact edits with a one-click commit",
  C:"force-push", C_en:"Force-push",
  D:"刪除 issue", D_en:"Delete an issue",
  ans:"B",
  exp:"reviewer 在 diff 中提交內聯修改建議；作者點選 'Commit suggestion' 套用。",
  exp_en:"Reviewer proposes inline edits in the diff; author clicks 'Commit suggestion' to apply." },
{ type:"single",
  stem:"fork workflow 中，origin 與 upstream 通常分別代表？",
  stem_en:"In a fork workflow, what do `origin` and `upstream` usually refer to?",
  A:"origin=官方 repo, upstream=你的 fork", A_en:"origin=official repo, upstream=your fork",
  B:"origin=你的 fork, upstream=官方 repo", B_en:"origin=your fork, upstream=official repo",
  C:"兩者皆為官方 repo", C_en:"Both point to the official repo",
  D:"兩者皆為本地", D_en:"Both are local",
  ans:"B",
  exp:"先 clone 自己 fork（成為 origin），再手動 git remote add upstream <官方 URL>。",
  exp_en:"Clone your fork (which becomes origin), then `git remote add upstream <official>` manually." },
{ type:"single",
  stem:"優秀的 PR 描述應該包含哪一項最關鍵的內容？",
  stem_en:"A good PR description should ALWAYS include?",
  A:"作者個人興趣", A_en:"Author's personal interests",
  B:"變更動機與測試方式（What / Why / How tested）", B_en:"The change's motivation and how it was tested (What / Why / How tested)",
  C:"反 Git 之歌一首", C_en:"An anti-Git rant",
  D:"連結到無關的 repo", D_en:"Links to unrelated repos",
  ans:"B",
  exp:"reviewer 沒讀心術；description 是 PR 最主要的溝通工具。",
  exp_en:"Reviewers can't read minds — the description is the PR's primary communication channel." }
,
{ type:"multi",
  stem:"以下哪些屬於良好的 PR 寫作 / review 實踐？（多選）",
  stem_en:"Which are good PR-writing / review practices? (Multiple)",
  A:"PR 描述包含 What / Why / How tested 三段", A_en:"PR description with What / Why / How tested",
  B:"PR 變動行數控制在約 400 行以下", B_en:"Keep PR diffs around 400 lines or fewer",
  C:"review 期間 force-push 整理歷史", C_en:"Force-pushing during review to tidy history",
  D:"Reviewer 區分 nit 與 blocking 評論", D_en:"Reviewer distinguishes nit-pick from blocking comments",
  ans:["A","B","D"],
  exp:"C 會打斷 reviewer 的評論定位；其餘三者為公認最佳實踐。",
  exp_en:"C breaks reviewer comment anchors; the other three are well-established best practices." },
{ type:"tf",
  stem:"是非題：在 PR 描述中寫 \"Closes #N\"、\"Fixes #N\"、\"Resolves #N\" 三個關鍵字都可以在合併後自動關閉 issue #N。",
  stem_en:"True/False: Any of \"Closes #N\", \"Fixes #N\", or \"Resolves #N\" in a PR description will auto-close issue #N when merged.",
  ans:"T",
  exp:"GitHub 支援多個同義詞觸發自動關閉。",
  exp_en:"GitHub supports multiple synonymous keywords to trigger auto-close." }
],

"Step 9：.gitignore & Git LFS": [
{ type:"single",
  stem:"以下何種檔案最絕對不應該被 commit 進 Git？",
  stem_en:"Which file type should ABSOLUTELY NOT be committed to Git?",
  A:"analysis.R", A_en:"analysis.R",
  B:"environment.yml", B_en:"environment.yml",
  C:"raw_reads.fastq.gz（50 GB）", C_en:"raw_reads.fastq.gz (50 GB)",
  D:"README.md", D_en:"README.md",
  ans:"C",
  exp:"FASTQ 太大、且應存於 SRA/ENA 等公開資料庫，於 README 註記 accession。",
  exp_en:"FASTQ is too large and belongs in SRA/ENA — reference the accession in README." },
{ type:"single",
  stem:".gitignore 中以 ! 開頭的 pattern 是？",
  stem_en:"A pattern starting with `!` in .gitignore means?",
  A:"註解", A_en:"A comment",
  B:"否定（強制納入此檔案，即使先前規則排除）", B_en:"Negation — re-include this file even if previously excluded",
  C:"暫存", C_en:"Temporary",
  D:"重要", D_en:"Important",
  ans:"B",
  exp:"! 例：`*.pdf` 後接 `!figure_1.pdf` 表示忽略其他 pdf，但保留 figure_1。",
  exp_en:"Example: `*.pdf` then `!figure_1.pdf` ignores all PDFs except figure_1." },
{ type:"single",
  stem:"已誤 commit 一個 10 GB 的 BAM，最妥當的後續處理？",
  stem_en:"You accidentally committed a 10 GB BAM. Best follow-up?",
  A:"完全置之不理", A_en:"Ignore it",
  B:"git rm --cached 移出 index 並補 .gitignore，必要時用 git filter-repo 從歷史中徹底移除，並通知協作者重新 clone", B_en:"`git rm --cached`, add to .gitignore; if needed, purge history with `git filter-repo` and warn collaborators to re-clone",
  C:"git revert", C_en:"git revert",
  D:"git push --force 沒問題", D_en:"`git push --force` solves it",
  ans:"B",
  exp:"--cached 僅移出最新 index；過去歷史仍含此檔，要清掉得改寫歷史並協調。",
  exp_en:"--cached only removes from the current index — history still contains the file. Full purge needs history rewrite + coordination." },
{ type:"multi",
  stem:"以下哪些檔案類型適合放在 Git LFS？（多選）",
  stem_en:"Which file types are suitable for Git LFS? (Multiple)",
  A:"必須版本控管且 <1 GB 的訓練好模型", A_en:"Must-be-versioned trained model (<1 GB)",
  B:"raw FASTQ 50 GB", B_en:"50 GB raw FASTQ",
  C:"reference genome index 200 MB", C_en:"200 MB reference genome index",
  D:"專案 README.md", D_en:"Project README.md",
  ans:["A","C"],
  exp:"LFS 適合中等大小、必須版控的 binary；raw 大型 omics 資料應外部儲存；文字檔不需 LFS。",
  exp_en:"LFS suits medium-sized binary files that must be versioned; raw omics belongs outside; text files don't need LFS." },
{ type:"single",
  stem:"Jupyter notebook .ipynb 想 commit 但不想存大量 cell outputs，最佳做法？",
  stem_en:"Want to commit `.ipynb` notebooks but skip cell outputs — best approach?",
  A:"刪掉整個 notebook", A_en:"Delete the notebook",
  B:"使用 nbstripout（pre-commit hook）自動清除 outputs 後 commit", B_en:"Use nbstripout (as a pre-commit hook) to strip outputs before commit",
  C:"改寫成 .docx", C_en:"Convert to .docx",
  D:"全部加進 .gitignore", D_en:"Add everything to .gitignore",
  ans:"B",
  exp:"nbstripout 在 commit 前自動清空 outputs，保留 code 結構。",
  exp_en:"nbstripout strips outputs before each commit while preserving the code structure." },
{ type:"tf",
  stem:"是非題：GitHub 拒絕單一檔案 >100 MB 的 push（非 LFS 情況下）。",
  stem_en:"True/False: GitHub rejects pushes containing any single file >100 MB (without LFS).",
  ans:"T",
  exp:"硬限制 100 MB；常見地雷，誤 commit 後須先清歷史才能繼續 push。",
  exp_en:"Hard 100 MB limit; common pitfall — must rewrite history before pushing again." },
{ type:"single",
  stem:"啟用 Git LFS 並開始追蹤 *.h5 的正確順序？",
  stem_en:"Correct order to enable Git LFS and start tracking `*.h5`?",
  A:"git lfs install → git lfs track \"*.h5\" → commit .gitattributes → add 大檔 → commit", A_en:"`git lfs install` → `git lfs track \"*.h5\"` → commit .gitattributes → add big file → commit",
  B:"先 push 大檔 → 啟用 LFS", B_en:"Push the big file first, then enable LFS",
  C:"只要 git lfs push 就好", C_en:"Just run `git lfs push`",
  D:"無需 .gitattributes", D_en:".gitattributes is unnecessary",
  ans:"A",
  exp:".gitattributes 記錄哪些 pattern 走 LFS——必先 commit，否則大檔仍進 Git 主庫。",
  exp_en:".gitattributes records which patterns use LFS — must be committed first, else the big file lands in regular Git." },
{ type:"single",
  stem:"清理 Git 歷史中誤 commit 的大檔，現代官方推薦工具？",
  stem_en:"Modern tool recommended for purging accidentally committed big files from Git history?",
  A:"git filter-branch（已 deprecated）", A_en:"git filter-branch (deprecated)",
  B:"git filter-repo", B_en:"git filter-repo",
  C:"git rm（單獨）", C_en:"git rm alone",
  D:"git gc", D_en:"git gc",
  ans:"B",
  exp:"filter-repo 是 git 官方建議取代 filter-branch，速度快、API 清晰。",
  exp_en:"filter-repo is Git's recommended replacement for filter-branch — faster and cleaner API." },
{ type:"single",
  stem:"以下哪個 .gitignore 規則最能忽略 work/ 目錄下所有檔案？",
  stem_en:"Which .gitignore pattern best ignores everything inside `work/`?",
  A:"work*", A_en:"work*",
  B:"work/", B_en:"work/",
  C:"work.gitignore", C_en:"work.gitignore",
  D:".git/work", D_en:".git/work",
  ans:"B",
  exp:"`work/` 表示目錄忽略；多階 work/sub/ 也會自動忽略。",
  exp_en:"`work/` ignores the directory and everything nested below it." },
{ type:"multi",
  stem:"raw FASTQ 不應 commit，但你仍想讓他人能取得原始資料。下列哪些是合適做法？（多選）",
  stem_en:"Raw FASTQ shouldn't be committed but others need access. Which are good alternatives? (Multiple)",
  A:"上傳至 SRA / ENA / GEO 並於 README 註記 accession", A_en:"Deposit in SRA/ENA/GEO and reference accession in README",
  B:"存到實驗室 NAS，README 寫明路徑", B_en:"Store on lab NAS, mention path in README",
  C:"使用 Zenodo / Figshare 取得 DOI", C_en:"Use Zenodo / Figshare to mint a DOI",
  D:"全部塞進 Git LFS", D_en:"Push all of it through Git LFS",
  ans:["A","B","C"],
  exp:"raw FASTQ 通常超過 LFS 配額；外部公開資料庫 / NAS / Zenodo 才合理。",
  exp_en:"Raw FASTQ typically exceeds LFS quotas; external public DBs / NAS / Zenodo are appropriate." }
,
{ type:"multi",
  stem:".gitignore pattern 中以下哪些寫法正確會忽略所有 .fastq.gz 檔（不論深度）？（多選）",
  stem_en:"Which patterns correctly ignore all `.fastq.gz` files at any depth? (Multiple)",
  A:"*.fastq.gz", A_en:"*.fastq.gz",
  B:"**/*.fastq.gz", B_en:"**/*.fastq.gz",
  C:"data/raw/*.fastq.gz", C_en:"data/raw/*.fastq.gz",
  D:"!*.fastq.gz", D_en:"!*.fastq.gz",
  ans:["A","B"],
  exp:"A 不帶斜線時 gitignore 會在所有目錄套用；B 顯式遞迴。C 只覆蓋特定路徑；D 是負反向（強制納入）。",
  exp_en:"A applies at all depths when there's no slash; B is explicit recursion. C only covers a specific path; D is negation (force-include)." },
{ type:"tf",
  stem:"是非題：raw FASTQ 通常應該透過 SRA / ENA / GEO 提供公開存取，而非用 Git LFS 上傳。",
  stem_en:"True/False: Raw FASTQ should usually be deposited in SRA / ENA / GEO for public access, NOT pushed via Git LFS.",
  ans:"T",
  exp:"LFS 配額有限且非公開資料庫慣例；公開 omics 資料屬於 SRA / ENA / GEO。",
  exp_en:"LFS quotas are limited and it's not where the community looks for omics data; SRA / ENA / GEO are the canonical homes." }
]

      },
      "進階主題": {

"Advanced：Git 工作流程": [
{ type:"single",
  stem:"以下哪個是「最簡」、最廣泛適用於小團隊與單版本工具的 Git 工作流程？",
  stem_en:"Which is the SIMPLEST workflow, broadly suitable for small teams and single-version tools?",
  A:"Git Flow", A_en:"Git Flow",
  B:"GitHub Flow", B_en:"GitHub Flow",
  C:"Trunk-based", C_en:"Trunk-based",
  D:"Forking workflow", D_en:"Forking workflow",
  ans:"B",
  exp:"GitHub Flow 只需 main + 短壽命 feature 分支；最少儀式，最常用。",
  exp_en:"GitHub Flow needs only main + short-lived feature branches — minimal ceremony, most common." },
{ type:"single",
  stem:"Git Flow 的「長壽分支」有哪兩條？",
  stem_en:"Which two long-lived branches does Git Flow define?",
  A:"main 與 develop", A_en:"main and develop",
  B:"trunk 與 release", B_en:"trunk and release",
  C:"prod 與 staging", C_en:"prod and staging",
  D:"hotfix 與 feature", D_en:"hotfix and feature",
  ans:"A",
  exp:"Git Flow：main（已發布）+ develop（整合）為長壽；feature/release/hotfix 為短壽。",
  exp_en:"Git Flow: main (released) + develop (integration) are long-lived; feature/release/hotfix are short-lived." },
{ type:"single",
  stem:"版本 v1.4.2 修了 bug，新版本應是？",
  stem_en:"You fixed a bug in v1.4.2 — what should the next version be?",
  A:"v2.0.0", A_en:"v2.0.0",
  B:"v1.5.0", B_en:"v1.5.0",
  C:"v1.4.3", C_en:"v1.4.3",
  D:"v1.4.2-bugfix", D_en:"v1.4.2-bugfix",
  ans:"C",
  exp:"semver：PATCH 升級（最後一位）。",
  exp_en:"Semver: bump PATCH (last digit) for bug fixes." },
{ type:"single",
  stem:"Conventional Commits 中「feat!: change API」中的「!」表示？",
  stem_en:"In Conventional Commits, what does `!` in `feat!: change API` mean?",
  A:"驚嘆", A_en:"Excitement",
  B:"BREAKING CHANGE 標記", B_en:"BREAKING CHANGE marker",
  C:"未完成", C_en:"Incomplete",
  D:"已 revert", D_en:"Already reverted",
  ans:"B",
  exp:"! 等同於 commit body 含 BREAKING CHANGE：對應 semver MAJOR 升級。",
  exp_en:"! equals having BREAKING CHANGE in the body — triggers a semver MAJOR bump." },
{ type:"single",
  stem:"何時應該 git tag -a v1.0.0？",
  stem_en:"When should you `git tag -a v1.0.0`?",
  A:"任何時候", A_en:"Any time",
  B:"確認某個 commit 是發行版本，欲為其打上具備訊息的 annotated tag", B_en:"When a commit is a confirmed release version and deserves an annotated tag with a message",
  C:"當分支衝突時", C_en:"On branch conflicts",
  D:"當無法 push 時", D_en:"When pushes fail",
  ans:"B",
  exp:"-a 為 annotated tag，附作者、日期、訊息，是發行版本標準作法。",
  exp_en:"-a is an annotated tag with author/date/message — standard for release versions." },
{ type:"tf",
  stem:"是非題：trunk-based development 在沒有完備 CI 的環境中通常風險過高。",
  stem_en:"True/False: Trunk-based development is usually too risky without a robust CI pipeline.",
  ans:"T",
  exp:"頻繁直推 main 必須仰賴自動化測試；沒 CI 等於沒護欄。",
  exp_en:"Frequent commits to main rely on automated tests; no CI = no safety net." },
{ type:"single",
  stem:"GitHub Release 上發布 binary，最佳實踐？",
  stem_en:"Best practice when publishing binaries via GitHub Releases?",
  A:"直接 commit 大檔到 main", A_en:"Commit binaries to main",
  B:"先打 git tag，再用 gh release create 附上 binary 與 release notes", B_en:"Tag first, then `gh release create` with attached binaries and release notes",
  C:"用 PR 發布", C_en:"Publish via PR",
  D:"無法發布 binary", D_en:"Binaries can't be released",
  ans:"B",
  exp:"Release 將 tag + assets + notes 包成一致的單元；不污染 Git 歷史。",
  exp_en:"Release bundles tag + assets + notes consistently — keeps Git history clean." },
{ type:"single",
  stem:"分支命名 \"fix/issue-42-mt-threshold\" 屬於？",
  stem_en:"The branch name `fix/issue-42-mt-threshold` is which style?",
  A:"純隨機名稱", A_en:"Random naming",
  B:"基於 issue 編號的命名慣例", B_en:"Issue-based naming convention",
  C:"author-prefix", C_en:"Author-prefix",
  D:"release 命名", D_en:"Release naming",
  ans:"B",
  exp:"`fix/issue-N-short-desc` 方便回溯與 PR 描述自動引用 issue。",
  exp_en:"`fix/issue-N-short-desc` aids traceability and lets PRs auto-link the issue." },
{ type:"single",
  stem:"以下何者是「論文一次性專案」最合適的 Git 工作流？",
  stem_en:"Best Git workflow for a one-shot paper project?",
  A:"Git Flow（過度設計）", A_en:"Git Flow (over-engineered)",
  B:"GitHub Flow + 在投稿時打 tag/release snapshot", B_en:"GitHub Flow + tag/release snapshot at submission",
  C:"無需版本控管", C_en:"No version control needed",
  D:"每篇都新開 organization", D_en:"New organization per paper",
  ans:"B",
  exp:"簡潔；投稿、修訂、接受各打一個 tag，方便回追每個圖表所對應的 commit。",
  exp_en:"Simple; tag submission/revision/acceptance — each figure ties back to a commit." },
{ type:"multi",
  stem:"以下哪些屬於 Conventional Commit 的 type？（多選）",
  stem_en:"Which are valid Conventional Commit types? (Multiple)",
  A:"feat", A_en:"feat",
  B:"fix", B_en:"fix",
  C:"docs", C_en:"docs",
  D:"swag", D_en:"swag",
  ans:["A","B","C"],
  exp:"feat / fix / docs / refactor / test / chore / perf / build / ci 為常見 types。",
  exp_en:"feat / fix / docs / refactor / test / chore / perf / build / ci are common types." }
,
{ type:"multi",
  stem:"以下哪些是 Conventional Commits 的常用 type？（多選）",
  stem_en:"Which are common Conventional Commits types? (Multiple)",
  A:"feat", A_en:"feat",
  B:"fix", B_en:"fix",
  C:"refactor", C_en:"refactor",
  D:"chore", D_en:"chore",
  ans:["A","B","C","D"],
  exp:"feat / fix / docs / refactor / test / chore / perf / build / ci / style 為常見 types。",
  exp_en:"feat / fix / docs / refactor / test / chore / perf / build / ci / style are the common types." },
{ type:"tf",
  stem:"是非題：semver 中 MAJOR 升級代表「不向後相容的 API 變更」。",
  stem_en:"True/False: In semver, a MAJOR bump indicates a non-backwards-compatible API change.",
  ans:"T",
  exp:"MAJOR=breaking, MINOR=feature backwards-compatible, PATCH=fix backwards-compatible。",
  exp_en:"MAJOR=breaking, MINOR=feature backward-compatible, PATCH=bug fix backward-compatible." }
],

"Advanced：GitHub Actions & CI/CD": [
{ type:"single",
  stem:"GitHub Actions 的 workflow YAML 檔應放在 repo 的哪個路徑？",
  stem_en:"Where should workflow YAML files live in a repo for GitHub Actions?",
  A:"根目錄", A_en:"Repo root",
  B:".github/workflows/", B_en:".github/workflows/",
  C:"workflows/", C_en:"workflows/",
  D:".git/workflows/", D_en:".git/workflows/",
  ans:"B",
  exp:"GitHub 只掃描 .github/workflows/ 下的 .yml/.yaml；其他位置不會觸發。",
  exp_en:"GitHub only scans .github/workflows/ for .yml/.yaml files; other paths are ignored." },
{ type:"single",
  stem:"要在多 Python / OS 版本下重複跑同樣測試，使用哪個 workflow 特性？",
  stem_en:"To run the same tests across multiple Python / OS versions, which workflow feature?",
  A:"matrix strategy", A_en:"matrix strategy",
  B:"composite action", B_en:"composite action",
  C:"reusable workflow", C_en:"reusable workflow",
  D:"workflow_dispatch", D_en:"workflow_dispatch",
  ans:"A",
  exp:"strategy.matrix 將多維組合展開為平行 jobs。",
  exp_en:"strategy.matrix expands multi-dimensional combinations into parallel jobs." },
{ type:"single",
  stem:"想在 Actions 中安全使用 API token，正確做法？",
  stem_en:"To securely use an API token in Actions, the correct approach is?",
  A:"硬編碼在 YAML", A_en:"Hardcode it in YAML",
  B:"設為 repo 加密 Secret，於 step 內以 ${{ secrets.NAME }} 引用", B_en:"Store as an encrypted repo Secret; reference via `${{ secrets.NAME }}` in a step",
  C:"留言給 PI", C_en:"Email it to the PI",
  D:"放在 .gitignore 內", D_en:"Put it in .gitignore",
  ans:"B",
  exp:"Secrets 加密儲存，log 自動 redact；硬編碼會公開外洩。",
  exp_en:"Secrets are encrypted and auto-redacted in logs; hardcoding leaks them publicly." },
{ type:"multi",
  stem:"以下哪些 Action 對生物資訊有用？（多選）",
  stem_en:"Which Actions are useful for bioinformatics? (Multiple)",
  A:"r-lib/actions/setup-r", A_en:"r-lib/actions/setup-r",
  B:"mamba-org/setup-micromamba", B_en:"mamba-org/setup-micromamba",
  C:"snakemake/snakemake-github-action", C_en:"snakemake/snakemake-github-action",
  D:"actions/checkout", D_en:"actions/checkout",
  ans:["A","B","C","D"],
  exp:"以上四者全都是生資 workflow 常用 building block。",
  exp_en:"All four are common building blocks in bioinformatics workflows." },
{ type:"single",
  stem:"CI workflow 中常見的觸發事件 'on: pull_request' 表示？",
  stem_en:"What does `on: pull_request` mean for a workflow trigger?",
  A:"每次 PR 開啟、更新或重新開啟時執行", A_en:"Run when a PR is opened, updated, or reopened",
  B:"每次 commit 都執行", B_en:"Run on every commit",
  C:"只在 main push 時執行", C_en:"Run only on push to main",
  D:"手動觸發", D_en:"Manual trigger",
  ans:"A",
  exp:"pull_request 預設觸發 opened/synchronize/reopened；確保 PR 變動都被測試。",
  exp_en:"pull_request defaults to opened/synchronize/reopened — ensures every PR change is tested." },
{ type:"single",
  stem:"自動排程每週執行 workflow，應使用？",
  stem_en:"To run a workflow weekly on a schedule, use?",
  A:"on: push", A_en:"on: push",
  B:"on: schedule（cron 表達式）", B_en:"on: schedule (cron expression)",
  C:"on: pull_request", C_en:"on: pull_request",
  D:"on: weekly", D_en:"on: weekly",
  ans:"B",
  exp:"schedule 接收 cron；例：cron: '0 4 * * 1' 每週一 04:00 UTC 執行。",
  exp_en:"schedule takes cron syntax; e.g., cron: '0 4 * * 1' runs Mondays at 04:00 UTC." },
{ type:"single",
  stem:"GitHub-hosted Linux runner 對私有 repo 在免費方案下，每月計時為？",
  stem_en:"On the free plan, GitHub-hosted Linux runners for private repos provide how many minutes per month?",
  A:"100", A_en:"100",
  B:"2000", B_en:"2000",
  C:"無限", C_en:"Unlimited",
  D:"500", D_en:"500",
  ans:"B",
  exp:"private repo 免費 2000 min/月，macOS 10× 加成、Windows 2×；public repo 無限。",
  exp_en:"Private repos: 2000 min/mo free; macOS counts 10×, Windows 2×; public repos are unlimited." },
{ type:"single",
  stem:"Action 中 `${{ secrets.GITHUB_TOKEN }}` 是？",
  stem_en:"What is `${{ secrets.GITHUB_TOKEN }}` in an Action?",
  A:"必須手動建立的 token", A_en:"A token you must create manually",
  B:"workflow 執行時自動產生、預設權限可設定的 token", B_en:"A per-run, auto-generated token with configurable default permissions",
  C:"PAT", C_en:"A PAT",
  D:"已 deprecated", D_en:"Deprecated",
  ans:"B",
  exp:"每次 workflow run 自動發放，預設讀 repo；可在 permissions: 區塊限制範圍。",
  exp_en:"Auto-issued per workflow run with default read scope; tighten via `permissions:`." },
{ type:"tf",
  stem:"是非題：在本機用 nektos/act 可以模擬執行 GitHub Actions workflow，省去 push-then-debug 迴圈。",
  stem_en:"True/False: `nektos/act` lets you run GitHub Actions locally, avoiding the push-then-debug cycle.",
  ans:"T",
  exp:"act 用 Docker 重現 Actions 環境；雖非 100% 完美，但對 90% 場景已足夠。",
  exp_en:"`act` reproduces the Actions environment via Docker — covers ~90% of cases though not perfect." },
{ type:"single",
  stem:"README 中加上 ![CI](https://github.com/user/repo/actions/workflows/test.yml/badge.svg) 的目的？",
  stem_en:"Why add `![CI](https://.../badge.svg)` to your README?",
  A:"展示作者頭像", A_en:"To show author's avatar",
  B:"顯示最新 workflow 通過狀態，向使用者傳達專案健康度", B_en:"Show latest workflow pass/fail — signals project health to users",
  C:"加密 commit", C_en:"Encrypts commits",
  D:"變更 default branch", D_en:"Changes the default branch",
  ans:"B",
  exp:"badge 是 CI 文化中常見的「綠燈承諾」。",
  exp_en:"Badges are a community convention for advertising 'green CI'." }
,
{ type:"multi",
  stem:"以下哪些是 GitHub Actions workflow 合法的觸發事件？（多選）",
  stem_en:"Which are valid GitHub Actions workflow triggers? (Multiple)",
  A:"on: push", A_en:"on: push",
  B:"on: pull_request", B_en:"on: pull_request",
  C:"on: schedule", C_en:"on: schedule",
  D:"on: workflow_dispatch", D_en:"on: workflow_dispatch",
  ans:["A","B","C","D"],
  exp:"四者皆為合法事件；workflow_dispatch 為手動觸發。",
  exp_en:"All four are valid triggers; workflow_dispatch is the manual trigger." },
{ type:"tf",
  stem:"是非題：使用第三方 GitHub Action 時，安全做法是把版本 pin 到 commit SHA 而非 tag（如 v4），可避免 tag 被惡意改寫。",
  stem_en:"True/False: When using third-party Actions, pinning to a commit SHA (instead of a tag like v4) is safer because tags can be re-pointed.",
  ans:"T",
  exp:"SHA 不可變；tag 可被作者重新指向不同 commit——若帳號被入侵會擴散到所有使用者。",
  exp_en:"SHAs are immutable; tags can be re-pointed by the author — a compromised account would spread to all users." }
],

"Advanced：可重現研究": [
{ type:"single",
  stem:"想讓他人重建你 R 套件環境的精確版本，應提交哪個檔案？",
  stem_en:"To let others reproduce your exact R package environment, commit which file?",
  A:"renv.lock", A_en:"renv.lock",
  B:"DESCRIPTION", B_en:"DESCRIPTION",
  C:"sessionInfo.txt", C_en:"sessionInfo.txt",
  D:".Rprofile", D_en:".Rprofile",
  ans:"A",
  exp:"renv.lock 由 renv::snapshot() 產生，記錄每個套件來源與版本；renv::restore() 還原。",
  exp_en:"renv.lock comes from renv::snapshot()and stores each package source+version; renv::restore() rebuilds." },
{ type:"single",
  stem:"建立可攜性高的 conda 環境檔，最佳指令？",
  stem_en:"Best command for a portable conda environment file?",
  A:"conda env export > env.yml", A_en:"conda env export > env.yml",
  B:"conda env export --from-history > env.yml", B_en:"conda env export --from-history > env.yml",
  C:"conda list > env.yml", C_en:"conda list > env.yml",
  D:"無需匯出", D_en:"No export needed",
  ans:"B",
  exp:"--from-history 只保留你顯式安裝的套件，避免 OS-specific build pin。",
  exp_en:"--from-history captures only explicit user-installed packages, avoiding OS-specific build pins." },
{ type:"single",
  stem:"將 GitHub Release 自動歸檔為論文可引用的 DOI，使用？",
  stem_en:"To auto-archive a GitHub Release as a citable DOI, use?",
  A:"Zenodo（與 GitHub 整合）", A_en:"Zenodo (GitHub integration)",
  B:"Google Drive", B_en:"Google Drive",
  C:"Dropbox", C_en:"Dropbox",
  D:"Twitter", D_en:"Twitter",
  ans:"A",
  exp:"啟用 Zenodo integration 後，每個 Release 觸發歸檔並產 DOI。",
  exp_en:"Enabling Zenodo integration auto-archives each Release and issues a DOI." },
{ type:"single",
  stem:"GitHub 的 CITATION.cff 檔案功能為？",
  stem_en:"What is GitHub's CITATION.cff file for?",
  A:"列出貢獻者 email", A_en:"Lists contributor emails",
  B:"提供結構化引用資訊，GitHub 自動轉成「Cite this repository」按鈕", B_en:"Structured citation metadata — GitHub renders a 'Cite this repository' button",
  C:"控制 CI", C_en:"Controls CI",
  D:"管理 issue 標籤", D_en:"Manages issue labels",
  ans:"B",
  exp:"CITATION.cff YAML 格式由 Citation File Format 計畫定義。",
  exp_en:"CITATION.cff is YAML defined by the Citation File Format project." },
{ type:"multi",
  stem:"以下哪些做法有助於提升 bioinformatics pipeline 的可重現性？（多選）",
  stem_en:"Which practices improve bioinformatics pipeline reproducibility? (Multiple)",
  A:"提供 Dockerfile 或 Singularity recipe", A_en:"Provide a Dockerfile or Singularity recipe",
  B:"semver 打 release tag", B_en:"Tag releases with semver",
  C:"README 中明列 input data accession 與 checksums", C_en:"List input data accessions and checksums in README",
  D:"CI 跑小型測試 dataset", D_en:"Run a small test dataset in CI",
  ans:["A","B","C","D"],
  exp:"以上四者都是現代 reproducibility 工具箱的核心要素。",
  exp_en:"All four belong to the core modern reproducibility toolkit." },
{ type:"single",
  stem:"提供 raw 資料的最佳方式為何？",
  stem_en:"Best way to publish raw data?",
  A:"直接 commit 進 Git", A_en:"Commit it to Git directly",
  B:"上傳至公開資料庫（SRA/ENA/GEO）並於 README 註記 accession 與 checksum", B_en:"Deposit in public DBs (SRA/ENA/GEO) and reference accessions + checksums in README",
  C:"附在 supplementary 圖檔內", C_en:"Embed in supplementary figures",
  D:"放在私人 Dropbox 並寄連結", D_en:"Private Dropbox + email link",
  ans:"B",
  exp:"raw 資料屬於公開資料庫；README 提供可驗證的 accession 與 hash 是 reproducibility 慣例。",
  exp_en:"Raw data belongs in public DBs; README accessions + hashes are the reproducibility convention." },
{ type:"tf",
  stem:"是非題：將容器映像（Docker image）以 tag（如 myrepo:1.0.0）綁定到 Git release tag，是強化可重現性的有效做法。",
  stem_en:"True/False: Tagging Docker images (e.g., myrepo:1.0.0) to match Git release tags strengthens reproducibility.",
  ans:"T",
  exp:"image SHA digest 與 commit SHA 對齊，使任何人都能完全重現 software stack。",
  exp_en:"Aligning image SHA digests with commit SHAs lets anyone reproduce the full software stack." },
{ type:"single",
  stem:"FAIR 原則中的 \"A\" 指的是？",
  stem_en:"In FAIR data principles, what does 'A' stand for?",
  A:"Authentic", A_en:"Authentic",
  B:"Accessible", B_en:"Accessible",
  C:"Annotated", C_en:"Annotated",
  D:"Anonymous", D_en:"Anonymous",
  ans:"B",
  exp:"FAIR：Findable / Accessible / Interoperable / Reusable。",
  exp_en:"FAIR: Findable / Accessible / Interoperable / Reusable." },
{ type:"single",
  stem:"Apptainer（前身 Singularity）相對於 Docker 的主要優點？",
  stem_en:"Main advantage of Apptainer (formerly Singularity) over Docker?",
  A:"映像更大", A_en:"Larger images",
  B:"無需 root 即可執行，適合 HPC 環境", B_en:"Runs without root — suitable for HPC environments",
  C:"只能跑 Linux", C_en:"Linux only",
  D:"無法封裝套件", D_en:"Can't bundle packages",
  ans:"B",
  exp:"Docker 預設需要 daemon + root；Apptainer 設計為 rootless，HPC 友善。",
  exp_en:"Docker needs a daemon with root by default; Apptainer is rootless — HPC-friendly." },
{ type:"single",
  stem:"以下何者是 Peng (2011) 提出的「可重現性」與「可重複性」核心差別？",
  stem_en:"Per Peng (2011), the core distinction between 'reproducibility' and 'replicability' is?",
  A:"完全相同", A_en:"They are identical",
  B:"reproducibility = 同碼同資料同結果；replicability = 獨立另一團隊驗證結果", B_en:"reproducibility = same code/data/result; replicability = independent team verifies result",
  C:"replicability = 跑同一 Docker", C_en:"Replicability = running the same Docker image",
  D:"無法區分", D_en:"They can't be separated",
  ans:"B",
  exp:"reproducibility 是運算層的可重複；replicability 是科學層的可重現（同實驗、另一組）。",
  exp_en:"Reproducibility is computational repeatability; replicability is scientific re-verification by another group." }
,
{ type:"multi",
  stem:"以下哪些屬於 FAIR for Research Software 的四個原則？（多選）",
  stem_en:"Which are the four FAIR for Research Software principles? (Multiple)",
  A:"Findable", A_en:"Findable",
  B:"Accessible", B_en:"Accessible",
  C:"Interoperable", C_en:"Interoperable",
  D:"Reusable", D_en:"Reusable",
  ans:["A","B","C","D"],
  exp:"FAIR4RS 將 FAIR（資料 2016）擴展至研究軟體領域，四個首字母保留。",
  exp_en:"FAIR4RS extends the 2016 data FAIR principles to research software; the four initials are preserved." },
{ type:"tf",
  stem:"是非題：把 GitHub repo 透過 Zenodo 取得 DOI 後，論文應引用該 DOI 而非裸 GitHub URL。",
  stem_en:"True/False: After getting a DOI for a GitHub repo via Zenodo, papers should cite the DOI rather than the bare GitHub URL.",
  ans:"T",
  exp:"DOI 永久不變且歸檔；GitHub URL 可改名、轉移、甚至刪除。",
  exp_en:"DOIs are persistent and archived; GitHub URLs can be renamed, transferred, or deleted." }
]

      }
    }
  }
};
